import type { SchemaGraph } from '../schema-parsers/types';

export function toSqlDdl(graph: SchemaGraph): string {
  const lines: string[] = [];

  for (const table of graph.tables) {
    lines.push(`CREATE TABLE "${table.name}" (`);
    const colLines: string[] = [];

    for (const col of table.columns) {
      let def = `  "${col.name}" ${col.type}`;
      if (col.isPrimary) def += ' PRIMARY KEY';
      if (!col.nullable && !col.isPrimary) def += ' NOT NULL';
      if (col.isUnique && !col.isPrimary) def += ' UNIQUE';
      if (col.defaultValue !== undefined) def += ` DEFAULT ${col.defaultValue}`;
      colLines.push(def);
    }

    // Add FOREIGN KEY constraints
    const fkRelations = graph.relations.filter((r) => r.fromTable === table.id);
    for (const rel of fkRelations) {
      colLines.push(
        `  FOREIGN KEY ("${rel.fromColumn}") REFERENCES "${rel.toTable}" ("${rel.toColumn}")`
      );
    }

    lines.push(colLines.join(',\n'));
    lines.push(');\n');
  }

  return lines.join('\n');
}

export function toPrismaSchema(graph: SchemaGraph): string {
  const lines: string[] = ['// Generated by HysCode Schema Visualizer', ''];

  const relsByTable = new Map<string, typeof graph.relations>();
  for (const rel of graph.relations) {
    if (!relsByTable.has(rel.fromTable)) relsByTable.set(rel.fromTable, []);
    relsByTable.get(rel.fromTable)!.push(rel);
  }

  for (const table of graph.tables) {
    const pascal = table.name.charAt(0).toUpperCase() + table.name.slice(1);
    lines.push(`model ${pascal} {`);

    for (const col of table.columns) {
      const prismaType = sqlTypeToPrisma(col.type);
      let field = `  ${col.name}  ${prismaType}`;
      if (col.nullable) field += '?';
      if (col.isPrimary) field += '  @id';
      if (col.isUnique && !col.isPrimary) field += '  @unique';
      if (col.defaultValue !== undefined) field += `  @default(${col.defaultValue})`;
      lines.push(field);
    }

    // Add relation fields
    const rels = relsByTable.get(table.id) ?? [];
    for (const rel of rels) {
      const targetPascal = rel.toTable.charAt(0).toUpperCase() + rel.toTable.slice(1);
      lines.push(`  ${rel.toTable}  ${targetPascal}  @relation(fields: [${rel.fromColumn}], references: [${rel.toColumn}])`);
    }

    lines.push('}', '');
  }

  return lines.join('\n');
}

export function toDrizzleSchema(graph: SchemaGraph, dialect: 'sqlite' | 'pg' | 'mysql' = 'sqlite'): string {
  const factory = { sqlite: 'sqliteTable', pg: 'pgTable', mysql: 'mysqlTable' }[dialect];
  const imports = new Set<string>([factory]);
  const typeImports = new Set<string>();

  const tableBlocks: string[] = [];

  for (const table of graph.tables) {
    const colLines: string[] = [];
    for (const col of table.columns) {
      const { fn, imp } = drizzleColType(col.type, dialect);
      typeImports.add(imp);
      let chain = `.${fn}('${col.name}')`;
      if (col.isPrimary) chain += '.primaryKey()';
      if (!col.nullable && !col.isPrimary) chain += '.notNull()';
      if (col.isUnique && !col.isPrimary) chain += '.unique()';
      if (col.defaultValue !== undefined) chain += `.default(${col.defaultValue})`;
      colLines.push(`  ${col.name}: ${chain},`);
    }
    tableBlocks.push(`export const ${table.name} = ${factory}('${table.name}', {\n${colLines.join('\n')}\n});\n`);
  }

  const importLine = `import { ${[...imports, ...typeImports].join(', ')} } from 'drizzle-orm/${dialect}-core';`;
  return [importLine, '', ...tableBlocks].join('\n');
}

export function toMermaidEr(graph: SchemaGraph): string {
  const lines: string[] = ['erDiagram'];

  for (const table of graph.tables) {
    lines.push(`  ${table.name} {`);
    for (const col of table.columns) {
      const type = col.type.split('(')[0].replace(/\s/g, '_');
      lines.push(`    ${type} ${col.name}${col.isPrimary ? ' PK' : col.isForeign ? ' FK' : ''}`);
    }
    lines.push('  }');
  }

  for (const rel of graph.relations) {
    const fromTable = graph.tables.find((t) => t.id === rel.fromTable)?.name ?? rel.fromTable;
    const toTable = graph.tables.find((t) => t.id === rel.toTable)?.name ?? rel.toTable;
    const arrow = rel.cardinality === '1-1' ? '||--||' : rel.cardinality === 'N-M' ? '}o--o{' : '||--o{';
    lines.push(`  ${fromTable} ${arrow} ${toTable} : "${rel.fromColumn}"`);
  }

  return lines.join('\n');
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function sqlTypeToPrisma(sqlType: string): string {
  const t = sqlType.toUpperCase().split('(')[0];
  const map: Record<string, string> = {
    INTEGER: 'Int', INT: 'Int', BIGINT: 'BigInt', SERIAL: 'Int', BIGSERIAL: 'BigInt',
    TEXT: 'String', VARCHAR: 'String', CHAR: 'String', UUID: 'String',
    REAL: 'Float', FLOAT: 'Float', DOUBLE: 'Float', NUMERIC: 'Decimal', DECIMAL: 'Decimal',
    BOOLEAN: 'Boolean', BOOL: 'Boolean',
    TIMESTAMP: 'DateTime', DATE: 'DateTime', TIME: 'String',
    JSON: 'Json', JSONB: 'Json',
    BLOB: 'Bytes', BINARY: 'Bytes',
  };
  return map[t] ?? 'String';
}

function drizzleColType(sqlType: string, dialect: string): { fn: string; imp: string } {
  const t = sqlType.toUpperCase().split('(')[0];
  const pgMap: Record<string, string> = {
    INTEGER: 'integer', INT: 'integer', BIGINT: 'bigint', SERIAL: 'serial', BIGSERIAL: 'bigserial',
    TEXT: 'text', VARCHAR: 'varchar', CHAR: 'char', UUID: 'uuid',
    REAL: 'real', FLOAT: 'doublePrecision', DOUBLE: 'doublePrecision', NUMERIC: 'numeric', DECIMAL: 'numeric',
    BOOLEAN: 'boolean', BOOL: 'boolean',
    TIMESTAMP: 'timestamp', DATE: 'date', TIME: 'time',
    JSON: 'json', JSONB: 'jsonb',
  };
  const sqliteMap: Record<string, string> = {
    INTEGER: 'integer', INT: 'integer', REAL: 'real', TEXT: 'text', BLOB: 'blob',
    VARCHAR: 'text', BOOLEAN: 'integer', BOOL: 'integer', TIMESTAMP: 'text', UUID: 'text', JSON: 'text',
  };
  const fn = dialect === 'sqlite' ? (sqliteMap[t] ?? 'text') : (pgMap[t] ?? 'text');
  return { fn, imp: fn };
}
