/** @type { import('tailwindcss').Config } */
module.exports = {
   // NativeWind v4: scan all JS/TS files in the project
   content: [
      './src/**/*.{ js,jsx,ts,tsx }',
      './app/**/*.{ js,jsx,ts,tsx }',
   ],
   presets: [require('nativewind/preset')],
   theme: {
      extend: {
      colors: {
         // ── Extracted from home.html (Hyska Neomorphic palette) ────────────
         'surface-dim': '#d4d6dc',
         'surface-container-lowest': '#f0f2f8',
         'secondary': '#6c6e7e',
         'on-primary-container': '#e0e2ff',
         'surface': '#e8eaf0',
         'on-primary-fixed-variant': '#4338ca',
         'on-error': '#ffffff',
         'surface-bright': '#edeef4',
         'surface-container-highest': '#d6d8de',
         'on-tertiary-fixed': '#2e1065',
         'surface-container-low': '#e5e7ed',
         'primary': '#6366f1',
         'background': '#e8eaf0',
         'on-tertiary-fixed-variant': '#5b21b6',
         'on-secondary': '#ffffff',
         'primary-container': '#818cf8',
         'inverse-surface': '#2e3040',
         'inverse-primary': '#a5b4fc',
         'inverse-on-surface': '#e8eaf0',
         'on-primary': '#ffffff',
         'on-error-container': '#991b1b',
         'secondary-fixed-dim': '#b8baca',
         'outline': '#8a8c9a',
         'primary-fixed': '#e0e2ff',
         'on-tertiary-container': '#3b1f63',
         'on-surface-variant': '#585a68',
         'on-secondary-fixed': '#1a1b26',
         'on-primary-fixed': '#1e1b4b',
         'on-surface': '#2e3040',
         'error': '#dc2626',
         'secondary-container': '#d8dae6',
         'on-secondary-container': '#585a68',
         'primary-fixed-dim': '#a5b4fc',
         'on-background': '#2e3040',
         'outline-variant': '#d0d2dc',
         'on-tertiary': '#ffffff',
         'surface-container': '#e2e4ea',
         'tertiary': '#7c3aed',
         'surface-container-high': '#dcdee4',
         'on-secondary-fixed-variant':'#404252',
         'tertiary-container': '#a78bfa',
         'secondary-fixed': '#d8dae6',
         'error-container': '#fee2e2',
         'tertiary-fixed': '#ede9fe',
         'surface-variant': '#dcdee4',
         'tertiary-fixed-dim': '#c4b5fd',
         'surface-tint': '#6366f1',
      },
      fontFamily: {
         headline: ['PlusJakartaSans_700Bold'],
         body: ['PlusJakartaSans_400Regular'],
         label: ['PlusJakartaSans_500Medium'],
      },
      borderRadius: {
         DEFAULT: '0.5rem',
         lg: '1rem',
         xl: '1.5rem',
         full:'9999px',
      },
      boxShadow: {
         'neo-raised': '6px 6px 12px rgba(0,0,0,0.08), -6px -6px 12px rgba(255,255,255,0.6)',
         'neo-inset': 'inset 4px 4px 8px rgba(0,0,0,0.06), inset -4px -4px 8px rgba(255,255,255,0.5)',
      },
      },
   },
   plugins: [],
};
